config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :users
  resources :ratings
  resources :comments
  resources :comments
  resources :swits

  get 'sweet' => 'swits#sweet'

  get 'sour' => 'swits#sour'

  get 'login' => 'session#new'

  post 'login' => 'session#create'

  post 'signup' => 'users#create'

  get 'logout' => 'session#destroy'

  post 'post_swit' => 'swits#post_swit'

  get 'home' => 'users#home'

  post 'swits/comment'

  get 'tags/get_swits/:text' => 'tags#get_swits'

  root 'session#index'

end

app/models/swit.rb
class Swit < ActiveRecord::Base
  belongs_to :user
  has_many :ratings, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :tags, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/controllers/swits_controller.rb
class SwitsController < ApplicationController
  before_action :set_swit, only: [:show, :edit, :update, :destroy]

  # GET /swits
  # GET /swits.json
  def index
    @swits = Swit.all
  end

  # GET /swits/1
  # GET /swits/1.json
  def show
  end

  # GET /swits/new
  def new
    @swit = Swit.new
  end

  # GET /swits/1/edit
  def edit
  end

  # POST /swits
  # POST /swits.json
  def create
    @swit = Swit.new(swit_params)

    respond_to do |format|
      if @swit.save
        flash[:success] = 'Swit was successfully created.'
        format.html { redirect_to @swit }
        format.json { render :show, status: :created, location: @swit }
      else
        format.html { render :new }
        format.json { render json: @swit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /swits/1
  # PATCH/PUT /swits/1.json
  def update
    respond_to do |format|
      if @swit.update(swit_params)
        flash[:success] = 'Swit was successfully updated.'
        format.html { redirect_to @swit }
        format.json { render :show, status: :ok, location: @swit }
      else
        format.html { render :edit }
        format.json { render json: @swit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /swits/1
  # DELETE /swits/1.json
  def destroy
    @swit.destroy
    @swits = Swit.all
    
    respond_to do |format|
      format.js
    end
  end

  def post_swit
    @current_user = User.find(session[:user_id])
    @current_swit = @current_user.swits.create(content: params[:content])

    # Find tags
    params[:content].scan(/\{.*?\}/).each do |tag|
      @current_swit.tags.create(content: tag)
    end

    @swits = Swit.all

    respond_to do |format|
      format.js
    end

  end

  def sweet
    @current_user = User.find(session[:user_id])
    @current_swit = Swit.find(params[:swit_id])
    temp = @current_swit.ratings.find_or_create_by(:user_id => @current_user.id)
    temp.update_attributes(:rate => '1')
    
    @swits = Swit.all

    respond_to do |format|
      format.js
    end
  end

  def sour
    @current_user = User.find(session[:user_id])
    @current_swit = Swit.find(params[:swit_id])
    temp = @current_swit.ratings.find_or_create_by(:user_id => @current_user.id)
    temp.update_attributes(:rate => '0')
    
    @swits = Swit.all

    respond_to do |format|
      format.js
    end
  end

  def comment
    @current_user = User.find(session[:user_id])
    @current_swit = Swit.find(params[:swit_id])
    @current_swit.comments.create(content: params[:content], user_id: session[:user_id])

    @swits = Swit.all

    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_swit
      @swit = Swit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def swit_params
      params.require(:swit).permit(:user_id, :content)
    end
end

app/helpers/swits_helper.rb
module SwitsHelper
end

app/views/swits/_form.html.haml
= form_for @swit do |f|
  - if @swit.errors.any?
    #error_explanation
      %h2= "#{pluralize(@swit.errors.count, "error")} prohibited this swit from being saved:"
      %ul
        - @swit.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.text_field :user_id
  .field
    = f.label :content
    = f.text_field :content
  .actions
    = f.submit 'Save'

app/views/swits/_form2.html.haml
= form_for @swit do |f|
  - if @swit.errors.any?
    #error_explanation
      %h2= "#{pluralize(@swit.errors.count, "error")} prohibited this swit from being saved:"
      %ul
        - @swit.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content
    = f.text_field :content
  .actions
    = f.submit 'Swit'

app/views/swits/_swit.html.haml
%ul{:id => "swit-#{swit.id}"}
  %span.user= link_to swit.user.username, swit.user
  %span.swit-content #{swit.content}
  
  %br

  = link_to "Sweet [" + swit.ratings.where(:rate => true).count.to_s + "]", sweet_path(swit_id: swit.id), :remote => true
  \|
  = link_to "Sour [" + swit.ratings.where(:rate => false).count.to_s + "]", sour_path(swit_id: swit.id), :remote => true
  \|
  = link_to "Delete", swit, :method => :delete, :remote => true, :data => { :confirm => 'Are you sure?' }

  %br

  - if swit.comments.any?
    %ol.comments= render swit.comments

  %br

  = form_tag swits_comment_path, remote: true, class: "form-inline" do
    = hidden_field_tag :swit_id, swit.id
    .input-group
      = text_field_tag :content1, params[:content1], class: "form-control", id: "comment-field"
      %span.input-group-btn
        = submit_tag "Comment", class: "btn btn-primary"

  %br

  %span.timestamp
    Posted #{time_ago_in_words(swit.created_at)} ago.

%hr

app/views/swits/comment.js.erb
$(".field #content").val("");

$('.swits').html("<%= j render @swits %>");

app/views/swits/destroy.js.erb
$('.swits').html("<%= j render @swits %>");

app/views/swits/edit.html.haml
%h1 Editing swit

= render 'form'

= link_to 'Show', @swit
\|
= link_to 'Back', swits_path

app/views/swits/index.html.haml
%h1 Listing swits

%table
  %thead
    %tr
      %th User
      %th Content
      %th
      %th
      %th

  %tbody
    - @swits.each do |swit|
      %tr
        %td= swit.user
        %td= swit.content
        %td= link_to 'Show', swit
        %td= link_to 'Edit', edit_swit_path(swit)
        %td= link_to 'Destroy', swit, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Swit', new_swit_path

app/views/swits/new.html.haml
%h1 New swit

= render 'form'

= link_to 'Back', swits_path

app/views/swits/post_swit.js.erb
$('#content').val("");

$('.swits').html("<%= j render @swits %>");

app/views/swits/show.html.haml
%p#notice= notice

%p
  %b User:
  = @swit.user
%p
  %b Content:
  = @swit.content

= link_to 'Edit', edit_swit_path(@swit)
\|
= link_to 'Back', swits_path

app/views/swits/sour.js.erb
$('.swits').html("<%= j render @swits %>");

app/views/swits/sweet.js.erb
$('.swits').html("<%= j render @swits %>");