config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :users
  resources :ratings
  resources :comments
  resources :comments
  resources :swits

  get 'sweet' => 'swits#sweet'

  get 'sour' => 'swits#sour'

  get 'login' => 'session#new'

  post 'login' => 'session#create'

  post 'signup' => 'users#create'

  get 'logout' => 'session#destroy'

  post 'post_swit' => 'swits#post_swit'

  get 'home' => 'users#home'

  post 'swits/comment'

  get 'tags/get_swits/:text' => 'tags#get_swits'

  root 'session#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :swits, dependent: :destroy

	has_secure_password

	validates_confirmation_of :password

	validates_uniqueness_of :username
	validates_presence_of :username

	validates_length_of :password, :in => 6..20, :on => :create

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  skip_before_filter :require_login, only: [:new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @swits = @user.swits.paginate(page: params[:page])
    # @comments = Comments.all
  end

  def home
    @user = User.find(session[:user_id])
    @swits = Swit.all.paginate(page: params[:page])
    # @comments = Comments.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        flash[:sucess] = 'User was successfully created.'
        login @user
        format.html { redirect_to home_path }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        flash[:success] = 'User was successfully updated.'
        format.html { redirect_to home_path }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      flash[:sucess] = 'User was successfully destroyed.'
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .actions
    = f.submit 'Save'

app/views/users/_form2.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
          
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .actions
    = f.submit 'Save'

app/views/users/_switform.html.haml
= form_tag post_swit_path, remote: true, id: "swit-form" do
  .swit-form
    .message
      %textarea.form-control#content{:maxlength => "140", :name => "content", :rows => '4'}
    .swit-bottom
      .countdown
      = submit_tag "Swit!", class: "btn btn-primary", id: "post-swit-button"

app/views/users/edit.html.haml
%h1 Editing user

= render 'form2'

= link_to 'Back', @user

app/views/users/home.html.haml
- provide(:title, @user.username)
.row
  %aside.col-md-4
    %section.user_info
      %h1
        = @user.username
  .col-md-8
    %h3
    = render 'switform'
    %ol.swits= render @swits
    = will_paginate @swits

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Username
      / %th Password
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.username
        / %td= user.password
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
/ %p#notice= notice

/ %p
/   %b Username:
/   = @user.username
/ %p
/   %b Password:
/   = @user.password
/ = link_to 'Home', home_path
/ \|
/ = link_to 'Change Password', edit_user_path(@user)
/ \|
/ / = link_to 'Back', users_path
/ = link_to 'Logout', logout_path

%br

- provide(:title, @user.username)
.row
  %aside.col-md-4
    %section.user_info
      %h1
        = @user.username
  .col-md-8
    - if @user.swits.any?
      %h3
        Swits (#{@user.swits.count})
      %ol.swits= render @swits
      = will_paginate @swits