config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :users
  resources :ratings
  resources :comments
  resources :comments
  resources :swits

  get 'sweet' => 'swits#sweet'

  get 'sour' => 'swits#sour'

  get 'login' => 'session#new'

  post 'login' => 'session#create'

  post 'signup' => 'users#create'

  get 'logout' => 'session#destroy'

  post 'post_swit' => 'swits#post_swit'

  get 'home' => 'users#home'

  post 'swits/comment'

  get 'tags/get_swits/:text' => 'tags#get_swits'

  root 'session#index'

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :swit
  belongs_to :user
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]

  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:swit_id, :user_id, :rate)
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.haml
= form_for @rating do |f|
  - if @rating.errors.any?
    #error_explanation
      %h2= "#{pluralize(@rating.errors.count, "error")} prohibited this rating from being saved:"
      %ul
        - @rating.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :swit
    = f.text_field :swit
  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :rate
    = f.check_box :rate
  .actions
    = f.submit 'Save'

app/views/ratings/edit.html.haml
%h1 Editing rating

= render 'form'

= link_to 'Show', @rating
\|
= link_to 'Back', ratings_path

app/views/ratings/index.html.haml
%h1 Listing ratings

%table
  %thead
    %tr
      %th Swit
      %th User
      %th Rate
      %th
      %th
      %th

  %tbody
    - @ratings.each do |rating|
      %tr
        %td= rating.swit
        %td= rating.user
        %td= rating.rate
        %td= link_to 'Show', rating
        %td= link_to 'Edit', edit_rating_path(rating)
        %td= link_to 'Destroy', rating, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Rating', new_rating_path

app/views/ratings/new.html.haml
%h1 New rating

= render 'form'

= link_to 'Back', ratings_path

app/views/ratings/show.html.haml
%p#notice= notice

%p
  %b Swit:
  = @rating.swit
%p
  %b User:
  = @rating.user
%p
  %b Rate:
  = @rating.rate

= link_to 'Edit', edit_rating_path(@rating)
\|
= link_to 'Back', ratings_path