config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :users
  resources :ratings
  resources :comments
  resources :comments
  resources :swits

  get 'sweet' => 'swits#sweet'

  get 'sour' => 'swits#sour'

  get 'login' => 'session#new'

  post 'login' => 'session#create'

  post 'signup' => 'users#create'

  get 'logout' => 'session#destroy'

  post 'post_swit' => 'swits#post_swit'

  get 'home' => 'users#home'

  post 'swits/comment'

  get 'tags/get_swits/:text' => 'tags#get_swits'

  root 'session#index'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :swit
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  def unique_tags
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def get_swits
    @user = User.find(session[:user_id])
    @tags = Tag.where(content: params[:text])
    @count = Tag.where(:content => params[:text]).count.to_s
    @text = params[:text]
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:swit_id, :content)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.haml
= form_for @tag do |f|
  - if @tag.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tag.errors.count, "error")} prohibited this tag from being saved:"
      %ul
        - @tag.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :swit
    = f.text_field :swit
  .field
    = f.label :content
    = f.text_field :content
  .actions
    = f.submit 'Save'

app/views/tags/edit.html.haml
%h1 Editing tag

= render 'form'

= link_to 'Show', @tag
\|
= link_to 'Back', tags_path

app/views/tags/get_swits.html.haml
- @tags.each do |tag|
  %ul{:id => "swit-#{tag.swit.id}"}
  %span.user= link_to tag.swit.user.username, tag.swit.user
  %span.swit-content #{tag.swit.content}
  
  %br

  = link_to "Sweet [" + tag.swit.ratings.where(:rate => true).count.to_s + "]", sweet_path(swit_id: tag.swit.id), :remote => true
  \|
  = link_to "Sour [" + tag.swit.ratings.where(:rate => false).count.to_s + "]", sour_path(swit_id: tag.swit.id), :remote => true
  \|
  = link_to "Delete", tag.swit, :method => :delete, :remote => true, :data => { :confirm => 'Are you sure?' }

  %br

  - if tag.swit.comments.any?
    %ol.comments= render tag.swit.comments

  %br

  = form_tag swits_comment_path, remote: true, class: "form-inline" do
    = hidden_field_tag :swit_id, tag.swit.id
    .form-group
      = text_field_tag :content, params[:content], class: "form-control"
    = submit_tag "Comment", class: "btn btn-primary"

  %br

  %span.timestamp
    Posted #{time_ago_in_words(tag.swit.created_at)} ago.

%hr

app/views/tags/index.html.haml
%h1 Listing tags

%table
  %thead
    %tr
      %th Swit
      %th Content
      %th
      %th
      %th

  %tbody
    - @tags.each do |tag|
      %tr
        %td= tag.swit
        %td= tag.content
        %td= link_to 'Show', tag
        %td= link_to 'Edit', edit_tag_path(tag)
        %td= link_to 'Destroy', tag, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Tag', new_tag_path

app/views/tags/new.html.haml
%h1 New tag

= render 'form'

= link_to 'Back', tags_path

app/views/tags/show.html.haml
%p#notice= notice

%p
  %b Swit:
  = @tag.swit
%p
  %b Content:
  = @tag.content

= link_to 'Edit', edit_tag_path(@tag)
\|
= link_to 'Back', tags_path